CC = gcc
CFLAGS = -Wall -lpthread

all: coffeeshop coffeeshop_semaphore

coffeeshop:
	$(CC) $(CFLAGS) -o coffeeshop coffeeshop.c
coffeeshop_semaphore:
	$(CC) $(CFLAGS) -o coffeeshop_semaphore coffeeshop_semaphore.c